---
  - hosts: all:!Ansible_Controller # bu taskler Ansible_Controller gurubu hariç 
                                   #inventory dosyasındaki tüm sunucular için geçerlidir.
    become: true
    tasks:

      # bu playdeki taskler sunucularda, paketleri ve paket indeksleri günceller.

      - name: Bu gorev, Ubuntu sunucularında Upgrade & Update işlemlerini yapar.
        ansible.builtin.package: 
          upgrade: dist # upgrade: dist ifadesi ile paketlerin dependencylerini de güncelleriz.
          update_cache: yes
        when: ansible_distribution == "Ubuntu" # işletim sistemi parametrelerinden dolayı koşul ifadesi kullanılmıştır.

      - name: Bu gorev, Rocky Linux sunucularında Upgrade & Update işlemlerini yapar.
        ansible.builtin.package: 
          update_only: yes # update_only: yes ifadesi ile paketlerin dependencylerini de güncelleriz.
          update_cache: yes
        when: ansible_distribution == "Rocky" # işletim sistemi parametrelerinden dolayı koşul ifadesi kullanılmıştır.

  # Bu rol Ansible_Controller grubundaki hostlar için kullanılmaktadır.

  - hosts: Ansible_Controller
    become: true
    connection: local
    roles:
      - Ansible_Controller