---

  - name: Bu Görev, Dosyadan değişkenleri okur.
    include_vars: /home/theadmin/AnsibleRolDosya/roles/vars/gitrepo.yml

  - name: Bu görev, Git repodan projenin kaynak kodlarını download eder.
    # Bu task bir download operasyonudur. wget tarzında bir işlem gerekitirir
    # Bu yüzden ansible içindeki git modülünü kullanacağız.
    git:
      repo: "{{ repoadres }}"
      dest: "{{ repoklasor }}"
      
  # Aşağıdaki task indirilen kaynak kodların listesini verir. Debug amaçlıdır.

  - name: Bu görev, github repodan indirilen proje belgelerini listeler.
    find:
      paths: "{{ repoklasor }}"
      register: liste # find modülünün kullanılması ile elde edilen çıktıları görüntülemek istiyoruz.

  - debug:
      var: liste